# Generated by Django 4.2 on 2025-11-07 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Post')),
                ('content', models.TextField(verbose_name='Relato de la Aventura')),
                ('destination', models.CharField(max_length=100, verbose_name='Destino')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='travel_images/', verbose_name='Imagen Principal')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post de Viaje',
                'verbose_name_plural': 'Posts de Viaje',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
