# Generated by Django 4.2 on 2025-11-07 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travels', '0002_travelpost_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post de Viaje', 'verbose_name_plural': 'Posts de Viaje'},
        ),
        migrations.RemoveField(
            model_name='travelpost',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='travelpost',
            name='destination',
        ),
        migrations.AddField(
            model_name='travelpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelpost',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Ubicación/Destino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='content',
            field=models.TextField(verbose_name='Contenido (Historia del Viaje)'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travels/images/', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
