# Generated by Django 4.2 on 2025-11-09 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travels', '0003_alter_travelpost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post de Viaje', 'verbose_name_plural': 'Posts de Viajes'},
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travel_pics/'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
