# Generated by Django 4.2 on 2025-11-10 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travels', '0004_alter_travelpost_options_alter_travelpost_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Publicación de Viaje', 'verbose_name_plural': 'Publicaciones de Viaje'},
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='content',
            field=models.TextField(verbose_name='Relato de la Aventura'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travel_pics/', verbose_name='Foto Principal'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Ubicación Principal'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título del Viaje'),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
    ]
