# Generated by Django 4.2 on 2025-11-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_alter_travelpost_options_alter_travelpost_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pie de foto'),
        ),
    ]
